{"uuid": "bfaaafc6-2321-42bf-8e98-6d1dec559a6a", "children": ["c8774aad-8a59-47cf-8578-f5b55e8d968f"], "befores": [{"name": "setup_class", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a6ee780>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/src/tests/base/android_base.py\", line 19, in setup_class\n    AndroidBaseTest.driver = webdriver.Remote(\"http://localhost:4723\", options=options)\n                             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/appium/webdriver/webdriver.py\", line 236, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        client_config=client_config,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/appium/webdriver/webdriver.py\", line 327, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 427, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n           ~~~~~~~~~~~~~~~~~~~~~~~~^\n        method, url, fields=fields, headers=headers, **urlopen_kw\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n    )\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1743274363822, "stop": 1743274363832}], "start": 1743274363822, "stop": 1743274364038}